spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 1710
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql

security:
  jwt:
    secret: amtkZmdmZGtnZDtmaGQ7aGtkZmtobGhkZmhkbGhXSjpMOkw=
    access: 360000
    refresh: 2592000000
